### ISSUE TITLE
HW 02.10.2017

### ISSUE THREAD

**Issue by AlexeyLukynchik** [IstiN/android-training-2017#1]
https://github.com/AlexeyLukynchik/happy_git/commits/master

**Comment by ilya-shknaj** [comment]
.local.properties shouldn't be pushed
you resolve conflicts wrong way. MainActivity.java.rej shouldn't be after conflicts resolving
MainActivity contain code that not compiling.
Resolve conflicts one more time

https://github.com/AlexeyLukynchik/happy_git containt link to submodule which containt .idea folder

**Comment by ilya-shknaj** [comment]
cherry pick commit should contain SHA of cherry picked commit, for example https://github.com/AlexandriaObraz/HomeWork/commit/d209655d3bbcb6bd25ab37418a2b0def89e2f680

**Comment by AlexeyLukynchik** [comment]
amended 
https://github.com/AlexeyLukynchik/Git_HW

**Comment by ilya-shknaj** [comment]
your code still not compiling
https://github.com/AlexeyLukynchik/Git_HW/blob/master/Git/app/src/main/java/com/example/lukyn/git/MainActivity.java

Try resolve conflicts one more time

**Comment by AlexeyLukynchik** [comment]
https://github.com/AlexeyLukynchik/Conflict

**Comment by ilya-shknaj** [comment]
verified
