### ISSUE TITLE
HW 02.10.2017

### ISSUE THREAD

**Issue by jauchenbusko** [IstiN/android-training-2017#10]
https://github.com/jauchenbusko/EpamHomeWork

**Comment by ilya-shknaj** [comment]
you don't commit project fully.
For example i don't see build.gradle file, without it project can't be compiled.
Easiest way to check that you commit all important files - remove local project, pull it from git and try to compile it.

**Comment by ilya-shknaj** [comment]
also you remove tests, that generated by default

**Comment by ilya-shknaj** [comment]
also i don't see that you try to resolve conflicts. Please do that again, or provide link to commit

**Comment by jauchenbusko** [comment]
1. Added gradle files
2. Link to commit with resolving conflict from other branch
https://github.com/jauchenbusko/EpamHomeWork/commit/1361a5e96624acdc6c2db21f45c1e161e155f0dd#diff-3b9587ce0950f6a9cc4f5d12986a67ad

**Comment by ilya-shknaj** [comment]
gitignore should contain app folder

**Comment by ilya-shknaj** [comment]
commit where you resolve conflicts should contain information about file where conflict happened (it generated by default in sourceTree)

**Comment by jauchenbusko** [comment]
Sorry, I've done the task via console cuz working on Linux platform. Check again, please.
(i added app folder to gitignore two)
https://github.com/jauchenbusko/EpamHomeWork/commit/818e91c395cd9f203a133c03b6658d4bae9be4d4

If you know any good Git GUI on linux, please let me know.

**Comment by ilya-shknaj** [comment]
good.
Unfortunately I don't have experience in git on Linux, but guys from my team recommend git gui
https://www.maketecheasier.com/6-useful-graphical-git-client-for-linux/
