### ISSUE TITLE
HW 02.10.2017

### ISSUE THREAD

**Issue by VasiliZ** [IstiN/android-training-2017#11]
https://github.com/VasiliZ/HomeWorks/commits/master

**Comment by ilya-shknaj** [comment]
you don't commit project fully.
For example i don't see build.gradle file, without it project can't be compiled.
Easiest way to check that you commit all important files - remove local project, pull it from git and try to compile it.

I can't find submodule

**Comment by VasiliZ** [comment]
@ilya-shknaj Сould you please recheck?

**Comment by ilya-shknaj** [comment]
checked
