### ISSUE TITLE
VCS task 02/10/2017

### ISSUE THREAD

**Issue by AndrewBogdanovich** [IstiN/android-training-2017#13]
https://github.com/AndrewBogdanovich/HWTask

**Comment by ilya-shknaj** [comment]
submodule contain .idea folder

**Comment by ilya-shknaj** [comment]
cherry pick commit should contain SHA of cherry picked commit, for example https://github.com/VladKudryshov/training-android/commit/679865e5bc2720932fba15090d17012b8e10ef68

Also I don't find commit that you cherry picked. Please try cherry pick one more time.

**Comment by AndrewBogdanovich** [comment]
updated, check please.

**Comment by ilya-shknaj** [comment]
done
