### ISSUE TITLE
HW: 23.11.2017

### ISSUE THREAD

**Issue by VasiliZ** [IstiN/android-training-2017#167]
@alexdzeshko 
Sample size calculation it works in this sample. 
For example. 
I'm get large image for different size imageview and get different value for opsion sample size
![image](https://user-images.githubusercontent.com/10958540/33378488-fed9264a-d525-11e7-9db1-35bb0153d93e.png)
self image: [picture](https://static.pexels.com/photos/33109/fall-autumn-red-season.jpg)

**Comment by alexdzeshko** [comment]
👍
