### ISSUE TITLE
HW: 02.10.2017

### ISSUE THREAD

**Issue by 5809909** [IstiN/android-training-2017#22]
https://github.com/5809909/HWork01-Git

**Comment by ilya-shknaj** [comment]
.idea in submodule

**Comment by 5809909** [comment]
.idea was removed from submodule
https://github.com/5809909/HelloWorld/tree/bc5e75bb87da3e7369388babe6788971b9fdf242

**Comment by 5809909** [comment]
.idea was removed from submodule
https://github.com/5809909/HelloWorld/tree/bc5e75bb87da3e7369388babe6788971b9fdf242

**Comment by ilya-shknaj** [comment]
done
