### ISSUE TITLE
HW 02.10.17 Git

### ISSUE THREAD

**Issue by MrMeowCat** [IstiN/android-training-2017#26]
https://github.com/MrMeowCat/Git_good

**Comment by ilya-shknaj** [comment]
submodule contain .idea folder
i don't see that you try cherry pick , rebase and stash
also commit where you resolve conflict should contain information about files where conflict happened, for example https://github.com/AlexandriaObraz/HomeWork/commit/d209655d3bbcb6bd25ab37418a2b0def89e2f680

**Comment by MrMeowCat** [comment]
Hi
Submodule is my other project, my bad about .idea.
I cherrypicked this commit from branch "f2" to master
https://github.com/MrMeowCat/Git_good/commit/c5318e886d54cbc542224e7374a2f4d0389a7c4f
I rebased master onto branch "rabase" and it appeared to have the same
commits as master.

**Comment by ilya-shknaj** [comment]
you can just remove .idea folder from submodule.
Also if you cherry pick something commit should contain SHA of cherry picked commit, for example https://github.com/VladKudryshov/training-android/commit/679865e

**Comment by MrMeowCat** [comment]
I did it via gitkraken, just clicked cherry pick and it copied into master.
Maybe missed something

7 окт. 2017 г. 12:53 ПП пользователь "ilya-shknaj" <notifications@github.com>
написал:

**Comment by ilya-shknaj** [comment]
submodule still contain .idea folder

**Comment by ilya-shknaj** [comment]
part about cherry pick - ok

**Comment by ilya-shknaj** [comment]
in future please comment when you fix comments
