### ISSUE TITLE
HW 02.10.17 GitOperations

### ISSUE THREAD

**Issue by iLyaTkachev** [IstiN/android-training-2017#27]
https://github.com/iLyaTkachev/GitOperationsEPAM

**Comment by ilya-shknaj** [comment]
submodule contain .idea folder

**Comment by ilya-shknaj** [comment]
In commit where you resolve conflict should contain information about files where conflict happened, for example https://github.com/AlexandriaObraz/HomeWork/commit/d209655d3bbcb6bd25ab37418a2b0def89e2f680

cherry pick commit should contain SHA of cherry picked commit, for example https://github.com/VladKudryshov/training-android/commit/679865e

**Comment by ilya-shknaj** [comment]
i don't see that you try rebase, stash

**Comment by iLyaTkachev** [comment]
https://github.com/iLyaTkachev/GitOperationsEPAM2

**Comment by iLyaTkachev** [comment]
decided to start again, most of the problems were caused by source tree. Android studio doesnt have such problems!

**Comment by ilya-shknaj** [comment]
I think with SourceTree all right :)
MainActivity.java.orig shouldn't be. Please remove it and try to resolve conflict one more time

**Comment by iLyaTkachev** [comment]
https://github.com/iLyaTkachev/GitOperationsEPAM2

resolved problems

**Comment by ilya-shknaj** [comment]
verified
