### ISSUE TITLE
HW 02.10.2017 Git

### ISSUE THREAD

**Issue by alexvishneuski** [IstiN/android-training-2017#28]
https://github.com/alexvishneuski/HelloGit.git

**Comment by ilya-shknaj** [comment]
.idea in submodule

**Comment by ilya-shknaj** [comment]
cherry pick commit should contain SHA of cherry picked commit, for example https://github.com/AlexandriaObraz/HomeWork/commit/d209655d3bbcb6bd25ab37418a2b0def89e2f680
I don't see that you try to use rebase

**Comment by alexvishneuski** [comment]
Thanks you for you comments.
Here is the link to [the cleaning .idea the submodule commit](https://github.com/alexvishneuski/HelloGit/commit/ae84652e8127df73671b9ff05da445b35f056deb).
Here is a link to [cherry pick](https://github.com/alexvishneuski/HelloGit/commit/afa9b8a7ce8d6bc04dd99d323f6316749bed3b0a).
Here is the link for rebase. [This commit of rebased branch.](https://github.com/alexvishneuski/HelloGit/commit/884b0117262ccc9ab926443dd8599669fc95ae1f)
[This commit of recipient branch.](https://github.com/alexvishneuski/HelloGit/commit/794f0dc67e7f91208184f0fc19a5a45d87406c2a)

**Comment by ilya-shknaj** [comment]
verified
