### ISSUE TITLE
MZ Task1

### ISSUE THREAD

**Issue by MorozikAlexander** [IstiN/android-training-2017#29]
https://github.com/MorozikAlexander/EpamAndroid.git

**Comment by ilya-shknaj** [comment]
I didn't find submodule

**Comment by ilya-shknaj** [comment]
still unresolved

**Comment by MorozikAlexander** [comment]
Hello! I decided to stop my investigation in Android till time that I improved my Java level, because it is not so high now. So, now I apply in Java training & if it will be success I'll continue learn Android. Thanks a lot for your attention to me. See you on next Android training!

**Comment by ilya-shknaj** [comment]
Good luck. I hope we will see you on next Android training
