### ISSUE TITLE
HW 02.10.2017

### ISSUE THREAD

**Issue by Dzmitry-Lakisau** [IstiN/android-training-2017#30]
https://github.com/DzmitryLakisau/HW01

**Comment by YauheniMeshkin** [comment]
in review

**Comment by YauheniMeshkin** [comment]
Please add SHA of cherry-picked commit, for example, VladKudryshov/training-android@679865e  and I didn't see where you resolved conflicts, please provide commit where will be described conflicts.

**Comment by Dzmitry-Lakisau** [comment]
1. SHA of cherry-picked commit can be see [in this commit](https://github.com/DzmitryLakisau/HW01/commit/fc89fde8d43b95edfb1c0fb3dc75f7dde10b40d7)
2. I successfully resolved conflict in file MainActivity.java before [this commit](https://github.com/DzmitryLakisau/HW01/commit/a311c60ebff0312caafc860891ca952aa7835fde). Or am I supposed to commit unresolved conflict to get my homework accepted, [like this](https://github.com/DzmitryLakisau/HW01/commit/9afea8d1850efa5bdd194331dc89cadfc9b5a729)?

**Comment by ilya-shknaj** [comment]
ok
