### ISSUE TITLE
HW_05.10.2017

### ISSUE THREAD

**Issue by ValeryiaKarpenko** [IstiN/android-training-2017#32]
https://github.com/ValeryiaKarpenko/MyCalc.git

**Comment by YauheniMeshkin** [comment]
Please add examples of spy, activityLifecycleMock with robolectric.. Please see http://robolectric.org/activity-lifecycle/

**Comment by ValeryiaKarpenko** [comment]
updated, check please.

**Comment by ilya-shknaj** [comment]
looks ok, but in future split method like testCalculaor to few separates, that check small part of you object
