### ISSUE TITLE
HW 02.10.2017

### ISSUE THREAD

**Issue by Darsha1509** [IstiN/android-training-2017#4]
https://github.com/Darsha1509/HWGit/commits/master

**Comment by ilya-shknaj** [comment]
submodule https://github.com/Darsha1509/NewsApp contain .idea folder

**Comment by ilya-shknaj** [comment]
herry pick commit should contain SHA of cherry picked commit, for example VladKudryshov/training-android@679865e

**Comment by Darsha1509** [comment]
https://github.com/Darsha1509/HWGit/commits/master

mistakes are fixed

**Comment by ilya-shknaj** [comment]
done
