### ISSUE TITLE
HW_05.10.2017

### ISSUE THREAD

**Issue by padlaboris** [IstiN/android-training-2017#44]
https://github.com/padlaboris/AndroidHomework/tree/HW2_05-10-2017

**Comment by MonchenkoID** [comment]
In review

**Comment by MonchenkoID** [comment]
please, add unitTest(mockito, robolectric). HW should contain examples of mock, spy, activityLifecycleMock with robolectric.

**Comment by MonchenkoID** [comment]
added TODO https://github.com/padlaboris/AndroidHomework/pulls

**Comment by padlaboris** [comment]
If I understand correctly there is example of spy Mockito
https://github.com/padlaboris/AndroidHomework/blob/HW2_05-10-2017/calculator/src/test/java/com/example/calculator/CalculatorTest.java
And example of mock and robolectric lifecycle
https://github.com/padlaboris/AndroidHomework/blob/HW2_05-10-2017/calculator/src/test/java/com/example/calculator/CalculatorActivityTest.java

**Comment by MonchenkoID** [comment]
Nice
