### ISSUE TITLE
HW: 09.10.2017

### ISSUE THREAD

**Issue by spaiker-grn** [IstiN/android-training-2017#63]
https://github.com/spaiker-grn/restaurants_menu.git

**Comment by YauheniMeshkin** [comment]
in verify

**Comment by YauheniMeshkin** [comment]
Good, but for the time you need use GSON type adapter (http://www.javacreed.com/gson-typeadapter-example/). Please add.

**Comment by spaiker-grn** [comment]
Hello, I remade TypeAdapter 
https://github.com/spaiker-grn/restaurants_menu/commit/525b2ebe5e38edcf39e5866b5049b5a6157d8e14

**Comment by ilya-shknaj** [comment]
verified
