### ISSUE TITLE
Google Cloud Module

### ISSUE THREAD

**Issue by VasiliZ** [IstiN/android-training-2017#67]
@YauheniMeshkin 
Please help with the installation of Google Cloud Module with Andriod Studio 3.
How it doing?

**Comment by YauheniMeshkin** [comment]
Please see https://androidstudio.googleblog.com/2017/08/android-studio-30-canary-9.html so we have two option: 
1. Using Firebase 
2. Create module on older version of android studio, import to your version and works as before

**Comment by VasiliZ** [comment]
@YauheniMeshkin thanks a lot
