### ISSUE TITLE
Problems with create class MyEndpoint.

### ISSUE THREAD

**Issue by Julia1632** [IstiN/android-training-2017#88]
When I create MyEndpoint, instead of MyEndpoint.class a MyEndpoint.java file is created that does not contain highlighting keywords. Can anyone help me to correct this.

**Comment by YauheniMeshkin** [comment]
@Julia1632  please provide the link on git with the issue, because I don't understand exactly what is wrong and which "highlighting keywords" you need.

**Comment by Julia1632** [comment]
![endpoint](https://user-images.githubusercontent.com/31549476/31634919-bb7053a8-b2cd-11e7-90d7-7d514faf607b.png)

https://github.com/Julia1632/Test_backend/blob/b1/backend/src/main/java/com/example/User/myapplication/backend/FieldsEndpoint.java

**Comment by YauheniMeshkin** [comment]
![image](https://user-images.githubusercontent.com/32477175/31636017-951dd85c-b2d1-11e7-8d37-48362b41d66a.png)
 For me works good, please try do Build-clean project and sync..

**Comment by Julia1632** [comment]
Nothing changed

**Comment by Julia1632** [comment]
Even when I download the archive from github and open it in Android Studio, the file doesn't change

**Comment by YauheniMeshkin** [comment]
Can you call me on skype (Yauheny_meshkin) and share the screen? It is the faster way because on git I don't see the issue.

**Comment by Julia1632** [comment]
Are you free now? Could I call you?

**Comment by YauheniMeshkin** [comment]
Yes, please send me message to skype for add to my contacts

**Comment by YauheniMeshkin** [comment]
correct skype yauheni_meshkin )

**Comment by Julia1632** [comment]
Nothing changed and the same problem with index.html
![image](https://user-images.githubusercontent.com/31549476/31657338-c9417534-b336-11e7-86fe-fca72dc14ec8.png)

**Comment by YauheniMeshkin** [comment]
index.html is correct for html file..   It seems a how locally problem, maybe with indexes. Did you try to create a new clean project and generate EndpointFile?

**Comment by Julia1632** [comment]
Yes, I tried.

**Comment by Julia1632** [comment]
Also there aren't created such class as
Request.class
RequestInitializer.class
ApiScopes.class

**Comment by YauheniMeshkin** [comment]
It seems how the problem with the android studio, please try reinstall android studio, and create this files again. If it didn't help you, please get tomorrow notebook, and I will try help you.

**Comment by Julia1632** [comment]
Reinstall didn't help

**Comment by YauheniMeshkin** [comment]
Resolved after discuss
